name = "oj-site-security"
main = "site-security-worker.js"
compatibility_date = "2026-09-27"
workers_dev = false

[[routes]]
pattern = "jc-oj.online/"
zone_name = "jc-oj.online"

[[routes]]
pattern = "jc-oj.online/index.html"
zone_name = "jc-oj.online"

[[routes]]
pattern = "jc-oj.online/admin.html"
zone_name = "jc-oj.online"
